name: deploy
on:
  push:
    branches: [main]
env:
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  DB_AWS_HOSTNAME: ${{ secrets.DB_AWS_HOSTNAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRE: ${{ secrets.JWT_EXPIRE }}
  HASH_SALT: ${{ secrets.HASH_SALT }}
jobs:
  deploy:
    runs-on: ['self-hosted', 'Linux', 'X64']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install npm packages
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Kill process
        run: fuser -k 3001/tcp
      - name: Run background
        run: RUNNER_TRACKING_ID="" && nohup npm run start:prod &
