name: deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version: '18'
      - name: Install npm packages
        run: cd /home/ubuntu/logineth && git pull && npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: fuser -k 3001/tcp && nohup npm run start:prod &
