name: deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: [self-hosted, Linux, x64]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '18'
      - name: Install npm packages
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          fuser -k 3001/tcp && nohup npm run start:prod &
