name: deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install npm packages
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Kill port
        run: fuser -k 3001/tcp
      - name: Run
        run: nohup npm run start:prod &
